In [1]:
import numpy as np

**Your First NumPy Array**

You're now going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code to create a numpy array from it?

* Import the numpy package as np, so that you can refer to numpy with np.
* Use np.array() to create a numpy array from baseball. Name this array np_baseball.
* Print out the type of np_baseball to check that you got it right.

In [2]:
# Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))
print(np_baseball)

<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


**Baseball players' height**

You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?



* Create a numpy array from height_in. Name this new array np_height_in.
* Print np_height_in.
* Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
* Print out np_height_m and check if the output makes sense.

In [4]:
height_in = [74, 72, 75, 71, 70, 73, 69, 76, 72, 74, 77, 78, 71, 73, 74, 75]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to metre: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 72 75 71 70 73 69 76 72 74 77 78 71 73 74 75]
[1.8796 1.8288 1.905  1.8034 1.778  1.8542 1.7526 1.9304 1.8288 1.8796
 1.9558 1.9812 1.8034 1.8542 1.8796 1.905 ]


**NumPy Side Effects**

numpy is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, numpy arrays cannot contain elements with different types. Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [5]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

**Subsetting NumPy Arrays**

Subsetting (using the square bracket notation on lists or arrays) works exactly the same with both lists and arrays.

This exercise already has two lists, height_in and weight_lb, loaded in the background for you. These contain the height and weight of the MLB players as regular lists. It also has two numpy array lists, np_weight_lb and np_height_in prepared for you.


* Subset np_weight_lb by printing out the element at index 50.
* Print out a sub-array of np_height_in that contains the elements at index 100 up to and including index 110.

Your First 2D NumPy Array
Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

Instructions
100 XP
Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
Print out the type of np_baseball.
Print out the shape attribute of np_baseball. Use np_baseball.shape.

In [12]:
# Example height data for MLB players (in inches)
height_in = [74, 72, 75, 71, 70, 73, 69, 76, 72, 74, 77, 78, 71, 73, 74, 75]

# Example weight data for MLB players (in pounds)
weight_lb = [180, 215, 210, 205, 195, 200, 185, 220, 190, 210, 230, 240, 210, 200, 215, 220]


np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 10
print(np_weight_lb[10])

# Print out sub-array of np_height_in: index 5 up to and including index 15
print(np_height_in [5:16])

230
[73 69 76 72 74 77 78 71 73 74 75]


**Your First 2D NumPy Array**

Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.

In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

* Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
* Print out the type of np_baseball.
* Print out the shape attribute of np_baseball. Use np_baseball.shape.

In [13]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
np_baseball.shape

<class 'numpy.ndarray'>


(4, 2)

**Subsetting 2D NumPy Arrays**

If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.

# numpy

import numpy as np

np_x = np.array(x)

np_x[:, 0]

The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.


* Print out the 50th row of np_baseball.
* Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
* Select the height (first column) of the 124th baseball player in np_baseball and print it out.






In [15]:
np_baseball = np.array(baseball)

# Print out the 3rd row of np_baseball
print(np_baseball[3, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)

# Print out height of 2 th player
print(np_baseball[2,0])

[188.   75.2]
[ 78.4 102.7  98.5  75.2]
210.0


**2D Arithmetic**

2D numpy arrays can perform calculations element by element, like numpy arrays.

np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height (in inches), weight (in pounds) and age (in years). baseball is available as a regular list of lists and updated is available as 2D numpy array.


* You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
* You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
* Multiply np_baseball with conversion and print out the result.

In [16]:
# Example data: 3 teams, 4 players per team, 3 attributes (height, weight, age)
baseball_data = [
    [
        [74, 180, 29], [72, 215, 30], [75, 210, 28], [71, 205, 31]
    ],
    [
        [70, 195, 32], [73, 200, 27], [69, 185, 29], [76, 220, 26]
    ],
    [
        [72, 190, 24], [74, 210, 25], [77, 230, 30], [78, 240, 28]
    ]
]


In [2]:
import numpy as np

# Example data for np_baseball (height in inches, weight in pounds, age in years)
baseball = [
    [74, 180, 29], [72, 215, 30], [75, 210, 28], [71, 205, 31],
    [70, 195, 32], [73, 200, 27], [69, 185, 29], [76, 220, 26]
]

# Convert baseball list of lists to a NumPy array
np_baseball = np.array(baseball)

# Example updated data for np_baseball (changes in height, weight, and age)
updated = np.array([
    [1, -5, 1], [2, 0, 0], [0, -10, 2], [-1, 5, -1],
    [3, 2, 1], [1, -4, 0], [2, 0, 0], [0, 0, 1]
])

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion (height in meters, weight in kilograms, age unchanged)
conversion = [0.0254, 0.453592, 1]

# Print out product of np_baseball and conversion
print(np_baseball * conversion)


[[ 75 175  30]
 [ 74 215  30]
 [ 75 200  30]
 [ 70 210  30]
 [ 73 197  33]
 [ 74 196  27]
 [ 71 185  29]
 [ 76 220  27]]
[[ 1.8796  81.64656 29.     ]
 [ 1.8288  97.52228 30.     ]
 [ 1.905   95.25432 28.     ]
 [ 1.8034  92.98636 31.     ]
 [ 1.778   88.45044 32.     ]
 [ 1.8542  90.7184  27.     ]
 [ 1.7526  83.91452 29.     ]
 [ 1.9304  99.79024 26.     ]]


Notice how with very little code, you can change all values in your numpy data structure in a very specific way. This will be very useful in your future as a data scientist!

**Average versus median**

You now know how to use numpy functions to get a better feeling for your data.

The baseball data is available as a 2D numpy array with 3 columns (height, weight, age) and 1015 rows. The name of this numpy array is np_baseball. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers. np_baseball is available.

* Create numpy array np_height_in that is equal to first column of np_baseball.
* Print out the mean of np_height_in.
* Print out the median of np_height_in.

In [3]:
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:, 0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

72.5
72.5


An average height of 1586 inches, that doesn't sound right, does it? However, the median does not seem affected by the outliers: 74 inches makes perfect sense. It's always a good idea to check both the median and the mean, to get an idea about the overall distribution of the entire dataset.



**Explore the baseball data**

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D NumPy array np_baseball, with three columns.

The Python script in the editor already includes code to print out informative messages with the different summary statistics and numpy is already loaded as np. Can you finish the job? np_baseball is available.

* The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.
* Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.
* Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.

In [4]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Average: 72.5
Median: 72.5
Standard Deviation: 2.29128784747792
Correlation: [[1.         0.47638349]
 [0.47638349 1.        ]]
